/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StencilPopup {
    'config': object;
    'dev': boolean;
    'open': (url: string, redirectUri?: string) => void;
  }
  interface StencilPopupAttributes extends StencilHTMLAttributes {
    'config'?: object;
    'dev'?: boolean;
    'onClosedPopup'?: (event: CustomEvent) => void;
    'onRedirectPopup'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'StencilPopup': Components.StencilPopup;
  }

  interface StencilIntrinsicElements {
    'stencil-popup': Components.StencilPopupAttributes;
  }


  interface HTMLStencilPopupElement extends Components.StencilPopup, HTMLStencilElement {}
  var HTMLStencilPopupElement: {
    prototype: HTMLStencilPopupElement;
    new (): HTMLStencilPopupElement;
  };

  interface HTMLElementTagNameMap {
    'stencil-popup': HTMLStencilPopupElement
  }

  interface ElementTagNameMap {
    'stencil-popup': HTMLStencilPopupElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
